Now in this notebook i am going to write the common parameteric machine learning methods. I will start off with regression,logistic regression,neural network,convolution neural network, finally RNN.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [49]:
#generating data for linear regression
np.random.seed(123)
input_val=np.random.uniform(1,100,100)
output=10*input_val+np.random.randn(100)

In [4]:
import theano.tensor as T
import theano

Now in theano we define graphs of computation what this means is that i define mathematical expression that do the computation. for evaluation of the mathematical expression i use the eval method of the expression.

In [5]:
X=T.vector(name="X",dtype=None)
print X

X


So above i have defined X as a theano vector, now when i print X then i get its name, there is no value attached with X. Such theano symbolic variables are called stateless, this means every time i want to evaluate X or any other symbolic expression.Then i will explicitly have to pass the input value for the expression. This is done via the eval method of the theano expression. The input to the eval method is the actual values for the variables present in the theano symbolic expression. The input is passed in as a dictionary.

In [10]:
X.eval({X:[1]})

array([ 1.])

Another type of theano variable is the shared variable, the shared variable have states. This means the actual value of the variables are stored in the memory. So this shared varaibles can be accessed by all the functions in the theano environment and also these variables can be updated by all the funcitons. One way to think about the shared variables is to think of them as global variables whose values are preserved in the memory. When i intialize the shared variable then i have to initialize the value of the shared variable also.

In [12]:
W1=theano.shared(np.random.rand(10,2),name="W1")


#note i can print the W1 var without passing the arguments to the eval method.
print W1.eval()

[[ 0.75160653  0.97055618]
 [ 0.97250295  0.98475057]
 [ 0.2125787   0.87757768]
 [ 0.37654479  0.26357592]
 [ 0.54958269  0.76609178]
 [ 0.3589441   0.88913325]
 [ 0.58314388  0.87209826]
 [ 0.13354264  0.90632715]
 [ 0.66870518  0.78033132]
 [ 0.81665128  0.27353627]]


In [61]:
#now this is all i need to do linear,logistic and neural network in thenao

X=T.vector(name="X",dtype=None)
y=T.vector(name="y",dtype=None)

#since w has to be changed at each iteration hence initializing a shared variable w

w=theano.shared(np.random.rand(1),name="w")

#prediction function

#y_hat=np.multiply(w,X)
y_hat=w*X

pred=theano.function(inputs=[X],outputs=y_hat)

cost=T.mean(T.sqr(y-y_hat))

gradient=T.grad(cost=cost,wrt=w)

updates=[[w,w-0.01*gradient]]


To do actual evaluation i can do it via two ways, the first way is to use the eval method. When I am using the eval method then i need to explicitly pass the input arg to the symbolic expression i want to evaluate. A much better way to do so is to use a theano.function. The input to the function is the list of actual input values, output is the symbolic variable i want to output. Once i have defined a theano.Function then i can use it just like any other python function syntax.

In [59]:
input_val1=input_val.reshape((100,1))
#w.get_value()*input_val1
pred(input_val)

array([ 13.07400123,   5.48147468,   4.38444307,  10.38814067,
        13.49957707,   8.01584192,  18.33444579,  12.85863106,
         9.08581331,   7.44243893,   6.53688827,  13.67685397,
         8.30201262,   1.29115199,   7.55210414,  13.84238044,
         3.56363422,   3.43337026,  10.02244926,  10.02756016,
        11.92552358,  15.90434044,  13.59184195,  11.49295965,
        13.55461403,   6.16276469,   6.8812497 ,   4.41056585,
         5.62163313,  11.86215225,   1.89116485,   8.21188088,
         8.15936046,   9.32179171,   8.06624224,   5.96482028,
         8.07588285,  16.71770435,  17.6571414 ,   9.4726242 ,
        11.73219919,   2.32624539,   6.05778651,   7.86262859,
        16.21663025,   4.82119738,   9.12471432,  18.4231808 ,
         9.79918166,  11.52757992,   2.41895279,  15.47707691,
        11.34560943,  10.27255388,   6.52922446,   5.81419399,
         7.9032622 ,  12.79333281,  16.38589416,   9.63148874,
        12.57153202,  11.02876384,  11.74978767,  12.67

In [62]:
train=theano.function(inputs=[X,y],outputs=cost,updates=updates)

In [63]:
for i in range(100):
    for a,b in zip(input_val,output):
        train(a,b)


TypeError: ('Bad input argument to theano function with name "<ipython-input-62-5a4bdbb92bfb>:1"  at index 0(0-based)', 'Wrong number of dimensions: expected 1, got 0 with shape ().')

In [42]:
X=T.scalar()
y=T.scalar()

def model(X,w):
    return X*w

w=theano.shared(np.asarray(0.0,dtype=theano.config.floatX))

y_hat=model(X,w)

cost=T.mean(T.sqr(y-y_hat))

gradient=T.grad(cost=cost,wrt=w)

updates=[[w,w-gradient*0.01]]

train=theano.function(inputs=[X,y],outputs=cost,updates=updates)


for i in range(100):
    for trX,trY in zip(input_val,output):
        train(trX,trY)

In [43]:
print w.get_value()

nan


In [44]:
from theano import tensor as T
import numpy as np

trX = np.linspace(-1, 1, 101)
trY = 2 * trX + np.random.randn(*trX.shape) * 0.33

X = T.scalar()
Y = T.scalar()

def model(X, w):
    return X * w

w = theano.shared(np.asarray(0., dtype=theano.config.floatX))
y = model(X, w)

cost = T.mean(T.sqr(y - Y))
gradient = T.grad(cost=cost, wrt=w)
updates = [[w, w - gradient * 0.01]]

train = theano.function(inputs=[X, Y], outputs=cost, updates=updates, allow_input_downcast=True)

for i in range(100):
    for x, y in zip(trX, trY):
        train(x, y)
        
print w.get_value()

2.02534637593


In [45]:
import 

(101,)

In [47]:
print input_val.shape
print output.shape

(100,)
(100,)


In [48]:
np.random.rand(100)

array([ 0.19133572,  0.67690586,  0.21550545,  0.27802359,  0.74176042,
        0.5597379 ,  0.33483641,  0.54298878,  0.6939847 ,  0.91213212,
        0.58071321,  0.23268638,  0.74669763,  0.77776902,  0.20040131,
        0.82057422,  0.46493485,  0.77976666,  0.23747822,  0.33258027,
        0.95369712,  0.65781507,  0.77287783,  0.68837434,  0.20430412,
        0.47068875,  0.80896387,  0.67503513,  0.00602789,  0.08740774,
        0.34679472,  0.94436554,  0.49119048,  0.27017627,  0.36042372,
        0.21065263,  0.42120006,  0.21803544,  0.84575251,  0.4562706 ,
        0.27980202,  0.93289165,  0.31435135,  0.90971466,  0.04341809,
        0.70711506,  0.48388904,  0.44422106,  0.03632334,  0.04068319,
        0.33275362,  0.94711954,  0.61765998,  0.36887484,  0.61197704,
        0.20613154,  0.16506644,  0.36181727,  0.86335335,  0.50940173,
        0.29690152,  0.95025163,  0.81596609,  0.32297394,  0.97209825,
        0.9873511 ,  0.40866013,  0.6559231 ,  0.4056532 ,  0.25

For better understanding of theano, I am going to implement the neural network as mentioned by denny britz. Once i am through the exact representation then i can move on with the linear and logit regression part of it.

In [66]:
X=T.matrix(name="X")
y=T.vector(name="y")

#the hidden dimension size is 100

In [67]:
#creating the shared variables for weights 
input_dim=1
hidden_dim=100
output_dim=1


W1=theano.shared(np.random.randn(input_dim,hidden_dim),name="W1")
b1=theano.shared(np.zeros(hidden_dim),name="b1")

W2=theano.shared(np.random.randn(hidden_dim,output_dim),name="W2")
b2=theano.shared(np.zeros(output_dim),name="b2")





In [69]:
#forward propogation

#hidden layer computation
z1=np.dot(X,W1)+b1
a1=T.tanh(z1)

#output layer computation
z2=np.dot(a1,W2)+b2
y_hat=T.nnet.softmax(z2)


ValueError: Cannot find a common data type.

(100, 1)